export type Entry={id:string;month:number;year?:number;kind:string;description:string;category:string;date:string;cents:number;paid:boolean;bank:string;source?:string;recurringFrom?:string;dateApproximate?:boolean;installmentGroup?:string;installmentNumber?:number;installmentCount?:number};
export type Finance={year:number;records:Entry[];categories:string[];banks:string[];cards:string[];monthlyTargets:number[];allocation:number[];essentialMonthlyCents:number;wealthCents:number;wealthGoals:number[];monthStates:string[];yearMonthStates?:Record<string,string>;sourceSheets:string[];help:string[]};
export const months=['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'];
export const kinds:Record<string,string>={fixed:'Despesa fixa',variable:'Despesa variável',card:'Fatura de cartão',income:'Recebimento',investment:'Investimento',reserve:'Depósito na reserva',investment_withdrawal:'Resgate de investimento',reserve_withdrawal:'Retirada da reserva'};
export const currency=(c:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(c/100);
export const isExpense=(r:Entry)=>['fixed','variable','card'].includes(r.kind);
export function monthState(state:Finance,year:number,month:number){return year===state.year?state.monthStates[month-1]:(state.yearMonthStates?.[`${year}-${month}`]||'previsto');}
export function createInstallments(state:Finance,entry:Entry,count:number){if(!Number.isInteger(count)||count<1||count>120)throw Error('Informe entre 1 e 120 parcelas.');if(count>1&&!isExpense(entry))throw Error('Parcelamento disponível apenas para despesas.');if(state.records.some(r=>r.id===entry.id)&&count>1)throw Error('Edite cada parcela existente individualmente.');const year=entry.year??state.year;if(year+Math.floor((entry.month-1+count-1)/12)>2100)throw Error('O parcelamento ultrapassa o ano 2100.');if(count===1)return updateEntry(state,entry);const result=structuredClone(state);const group=crypto.randomUUID();const day=entry.date?Number(entry.date.slice(8,10)):0;for(let i=0;i<count;i++){const monthIndex=entry.month-1+i;const y=year+Math.floor(monthIndex/12),m=monthIndex%12+1;const date=day?`${y}-${String(m).padStart(2,'0')}-${String(Math.min(day,new Date(Date.UTC(y,m,0)).getUTCDate())).padStart(2,'0')}`:'';result.records.push({...entry,id:i===0?entry.id:crypto.randomUUID(),year:y,month:m,date,paid:i===0?entry.paid:false,recurringFrom:undefined,installmentGroup:group,installmentNumber:i+1,installmentCount:count});}return result;}
export function investmentBalance(state:Finance){const contributions=state.records.filter(r=>r.kind==='investment').reduce((sum,r)=>sum+r.cents,0);const withdrawals=state.records.filter(r=>r.kind==='investment_withdrawal').reduce((sum,r)=>sum+r.cents,0);return {opening:state.wealthCents,contributions,withdrawals,total:state.wealthCents+contributions-withdrawals};}
export function reserveBalance(records:Entry[]){const deposits=records.filter(r=>r.kind==='reserve').reduce((sum,r)=>sum+r.cents,0);const withdrawals=records.filter(r=>r.kind==='reserve_withdrawal').reduce((sum,r)=>sum+r.cents,0);return {deposits,withdrawals,total:deposits-withdrawals};}
export function savedMovement(records:Entry[]){const t=totals(records);return t.invested-t.withdrawn;}
export function totals(records:Entry[]){const sum=(fn:(r:Entry)=>boolean)=>records.filter(fn).reduce((t,r)=>t+r.cents,0);const income=sum(r=>r.kind==='income'),expense=sum(isExpense),paid=sum(r=>isExpense(r)&&r.paid),invested=sum(r=>['investment','reserve'].includes(r.kind)),withdrawn=sum(r=>['investment_withdrawal','reserve_withdrawal'].includes(r.kind));return {income,expense,paid,pending:expense-paid,invested,withdrawn,cash:income-paid-invested+withdrawn,available:income-expense-invested+withdrawn};}
export function status(r:Entry,today=new Date().toLocaleDateString('en-CA',{timeZone:'America/Sao_Paulo'})){if(r.paid)return 'Pago';if(!r.date)return 'Sem data';if(r.date<today)return 'Vencido';if(r.date===today)return 'Vence hoje';const days=Math.round((Date.parse(r.date+'T12:00:00Z')-Date.parse(today+'T12:00:00Z'))/86400000);return `Vence em ${days} dias`;}
export function updateEntry(state:Finance,entry:Entry){const copy=structuredClone(state);const existing=copy.records.find(r=>r.id===entry.id);if(existing)Object.assign(existing,entry);else copy.records.push(entry);const visited=new Set<string>();const propagate=(id:string)=>{if(visited.has(id))return;visited.add(id);const parent=copy.records.find(r=>r.id===id)!;for(const child of copy.records.filter(r=>r.recurringFrom===id)){child.cents=parent.cents;child.description=parent.description;child.category=parent.category;if(parent.date){const [y,m,day]=parent.date.split('-').map(Number);const next=new Date(Date.UTC(y,m,Math.min(day,new Date(Date.UTC(y,m+1,0)).getUTCDate())));child.date=next.toISOString().slice(0,10);}else child.date='';propagate(child.id);}};propagate(entry.id);return copy;}
