import fs from 'node:fs';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import ts from 'typescript';
import {z} from 'zod';
const db=new DatabaseSync(':memory:');db.exec(fs.readFileSync('drizzle/0000_financial_state.sql','utf8'));
const storage=()=>({prepare:sql=>({bind:(...args)=>({run:async()=>({meta:{changes:Number(db.prepare(sql).run(...args).changes)}}),first:async()=>db.prepare(sql).get(...args)})})});
const financeJs=ts.transpileModule(fs.readFileSync('lib/finance.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText;
const finance=await import('data:text/javascript;base64,'+Buffer.from(financeJs).toString('base64'));
globalThis.financeTest={...finance,initial:JSON.parse(fs.readFileSync('lib/initial-data.json','utf8')),storage,z};
let source=ts.transpileModule(fs.readFileSync('app/api/state/route.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText;
source=source.replace(/^import .*;$/gm,'');source='const {initial,storage,z,investmentBalance,reserveBalance}=globalThis.financeTest;\n'+source;
const {GET,PUT}=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
let response=await GET();assert.equal(response.status,200);let result=await response.json();assert.equal(result.state.records.length,126);assert.equal(result.version,1);
const state=structuredClone(result.state);state.records[0].cents+=1;
const request=(state,version,origin='https://finance.test')=>new Request('https://finance.test/api/state',{method:'PUT',headers:{'Content-Type':'application/json',origin},body:JSON.stringify({state,version})});
assert.equal((await PUT(request(state,1))).status,200);assert.equal((await PUT(request(state,1))).status,409);
result=await (await GET()).json();assert.equal(result.state.records[0].cents,state.records[0].cents);assert.equal(result.version,2);
assert.equal((await PUT(request({...state,allocation:[50,30,30]},2))).status,400);
assert.equal((await PUT(request({...state,records:[...state.records,state.records[0]]},2))).status,400);
assert.equal((await PUT(request(state,2,'https://external.test'))).status,403);
assert.equal((await (await GET()).json()).version,2);
console.log('OK: SQL migration, persistent read/write, reload, version conflicts and input validation.');
